version : '3'

services:
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: msbatista
      ME_CONFIG_BASICAUTH_PASSWORD: 12345!!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: msbatista
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345!!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: msbatista
      MONGO_INITDB_ROOT_PASSWORD: 12345!!
    ports:
      - "27017:27017"
    volumes:
      - ${HOME}/.dev/docker/volumes/mongodb:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge